# PostgreSQL connection settings.
# CHANGE THESE THREE VALUES for your local database setup.
db.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.djaizsnanutxkubqccvv&password=uyPD0zQSVuJa2Y9l
db.user=postgres.djaizsnanutxkubqccvv
db.password=uyPD0zQSVuJa2Y9l
